(()=>{
const p=window.BOOK_PAGE;if(!p)return;
const app=document.getElementById('book-app');
const slug=s=>s.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML;};
const previous=p.number==='01'?'intro':('chapter'+(Number(p.number)-1));
const next=p.number==='10'?'TOC':('chapter'+(Number(p.number)+1));

const style=document.createElement('style');style.textContent=`
.reader-groups{margin-top:46px}.reader-group,.reader-subgroup{border-top:1px solid var(--line);padding:0}.reader-group>summary,.reader-subgroup>summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:20px;cursor:pointer}.reader-group>summary::-webkit-details-marker,.reader-subgroup>summary::-webkit-details-marker{display:none}.reader-group>summary{padding:27px 0}.reader-group-title{font-family:Georgia,'Times New Roman',serif;font-size:clamp(25px,4vw,36px);line-height:1.08;color:var(--ink)!important}.reader-group-mark{width:31px;height:31px;display:grid;place-items:center;border:1px solid var(--line);border-radius:50%;font-size:20px;color:#68757a;flex:none}.reader-group[open]>summary .reader-group-mark{background:var(--ocean);color:var(--white);transform:rotate(45deg)}.reader-children{padding:0 0 28px 25px}.reader-subgroup{border-left:1px solid var(--line);padding-left:20px;margin:0 0 8px;border-top:0}.reader-subgroup>summary{padding:16px 0;color:var(--ink)!important}.reader-subgroup-title{font-size:15px;font-weight:700;color:var(--ink)!important}.reader-subgroup-mark{font-size:20px;color:#68757a}.reader-subgroup[open]>summary .reader-subgroup-mark{transform:rotate(45deg)}.reader-leaf{display:block;padding:12px 0;color:#242829!important;text-decoration:none;font-family:Georgia,'Times New Roman',serif;font-size:18px;line-height:1.45;border-bottom:1px solid transparent}.reader-leaf:hover{color:var(--ink)!important}.chapter-footer{margin-top:60px}.reader h1{color:var(--ink)!important}.entrance{color:#3e4344!important}
`;document.head.appendChild(style);

function leafNode(item){const a=document.createElement('a');a.className='reader-leaf';a.id=slug(item.title);a.href='#'+slug(item.title);a.textContent=item.title;return a;}
function renderChildren(children,level=0){const frag=document.createDocumentFragment();children.forEach(item=>{if(item.children){const d=document.createElement('details');d.className=level===0?'reader-group':'reader-subgroup';d.id=slug(item.title);const s=document.createElement('summary');const title=document.createElement('span');title.className=level===0?'reader-group-title':'reader-subgroup-title';title.textContent=item.title;const mark=document.createElement('span');mark.className=level===0?'reader-group-mark':'reader-subgroup-mark';mark.textContent='+';s.append(title,mark);d.appendChild(s);const body=document.createElement('div');body.className='reader-children';body.appendChild(renderChildren(item.children,level+1));d.appendChild(body);frag.appendChild(d)}else frag.appendChild(leafNode(item))});return frag;}

const leaves=[];function collect(items){items.forEach(i=>i.children?collect(i.children):leaves.push(i.title));}collect(p.groups);
const first=leaves[0]||'';
app.innerHTML=`<header class="site-header"><a class="brand" href="https://propropro25.github.io/book/">A Theory of Integration</a><nav class="top-nav"><a href="https://propropro25.github.io/intro/">Author</a><a href="https://propropro25.github.io/TOC/">Contents</a><a href="https://propropro25.github.io/${p.sources}/">Evidence</a></nav></header><main class="reader"><div class="eyebrow">${esc(p.part)} · Chapter ${esc(p.number)}</div><h1>${esc(p.title)}</h1><div class="reader-groups"></div><nav class="chapter-footer"><a href="https://propropro25.github.io/${previous}/">← Previous</a><a href="https://propropro25.github.io/${next}/">Next →</a></nav></main>`;
const root=app.querySelector('.reader-groups');root.appendChild(renderChildren(p.groups));
})();
